version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: healmate_backend
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - qdrant
      - redis
      - postgres

  frontend:
    build:
      context: ./liff
      dockerfile: Dockerfile.frontend
    container_name: healmate_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./liff:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  qdrant:
    image: qdrant/qdrant:v1.14.1
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-healmate}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-healmate_pass}
      POSTGRES_DB: ${POSTGRES_DB:-healmate_db}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  qdrant_data:
  redis_data:
  pg_data: