version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:v1.14.1
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"   # REST / WebSocket API
      - "6334:6334"   # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-healmate}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-healmate_pass}
      POSTGRES_DB: ${POSTGRES_DB:-healmate_db}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  qdrant_data:
  redis_data:
  pg_data:
