name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 pytest pytest-asyncio

      - name: Lint (black)
        run: black --check .

      - name: Lint (isort)
        run: isort --check --profile black .

      - name: Lint (flake8)
        run: flake8 .

      - name: Run tests
        run: pytest -q
